export const cakes = [
  {
    id: 1,
    name: "Classic Vanilla Dream",
    category: "classic",
    price: 35,
    description: "A timeless vanilla sponge layered with silky vanilla buttercream and topped with fresh berries.",
    image: "/images/vanilla-cake.png",
    sizes: ["6 inch", "8 inch", "10 inch"],
    flavors: ["Vanilla", "French Vanilla", "Vanilla Bean"],
    featured: true,
  },
  {
    id: 2,
    name: "Chocolate Indulgence",
    category: "classic",
    price: 40,
    description: "Rich dark chocolate layers with ganache filling and a glossy chocolate mirror glaze.",
    image: "/images/chocolate-cake.png",
    sizes: ["6 inch", "8 inch", "10 inch"],
    flavors: ["Dark Chocolate", "Milk Chocolate", "White Chocolate"],
    featured: true,
  },
  {
    id: 3,
    name: "Strawberry Bliss",
    category: "fruit",
    price: 42,
    description: "Light strawberry sponge with fresh strawberry compote and whipped cream frosting.",
    image: "/images/strawberry-cake.png",
    sizes: ["6 inch", "8 inch", "10 inch"],
    flavors: ["Strawberry", "Strawberry Vanilla", "Strawberry Lemon"],
    featured: true,
  },
  {
    id: 4,
    name: "Red Velvet Elegance",
    category: "classic",
    price: 45,
    description: "Velvety red sponge with tangy cream cheese frosting and white chocolate shavings.",
    image: "/images/red-velvet-cake.png",
    sizes: ["6 inch", "8 inch", "10 inch"],
    flavors: ["Classic Red Velvet", "Red Velvet Chocolate"],
    featured: false,
  },
  {
    id: 5,
    name: "Lemon Sunshine",
    category: "fruit",
    price: 38,
    description: "Zesty lemon cake with lemon curd filling and meringue frosting, bright and refreshing.",
    image: "/images/lemon-cake.png",
    sizes: ["6 inch", "8 inch", "10 inch"],
    flavors: ["Lemon", "Lemon Raspberry", "Lemon Blueberry"],
    featured: false,
  },
  {
    id: 6,
    name: "Caramel Walnut Delight",
    category: "specialty",
    price: 48,
    description: "Moist caramel cake with crunchy walnut layers and salted caramel drizzle.",
    image: "/images/caramel-cake.png",
    sizes: ["6 inch", "8 inch", "10 inch"],
    flavors: ["Salted Caramel", "Caramel Pecan", "Butterscotch"],
    featured: false,
  },
  {
    id: 7,
    name: "Tiramisu Tower",
    category: "specialty",
    price: 50,
    description: "Coffee-soaked layers with mascarpone cream and dusted with cocoa powder.",
    image: "/images/tiramisu-cake.png",
    sizes: ["6 inch", "8 inch", "10 inch"],
    flavors: ["Classic Tiramisu", "Chocolate Tiramisu"],
    featured: true,
  },
  {
    id: 8,
    name: "Wedding White Rose",
    category: "wedding",
    price: 120,
    description: "Elegant three-tier white cake adorned with sugar roses and pearl details.",
    image: "/images/wedding-cake.png",
    sizes: ["3 tier", "4 tier", "5 tier"],
    flavors: ["Vanilla", "Almond", "Champagne"],
    featured: false,
  },
];

export const categories = [
  { id: "all", name: "All Cakes" },
  { id: "classic", name: "Classic" },
  { id: "fruit", name: "Fruit" },
  { id: "specialty", name: "Specialty" },
  { id: "wedding", name: "Wedding" },
];
